services:
  parakeet-rocm:
    build:
      context: .
      dockerfile: Dockerfile
    image: parakeet-rocm:latest
    container_name: parakeet-rocm
    ports:
      - "7862:7862" # Gradio
      - "8502:8502" # Streamlit
    environment:
      HSA_OVERRIDE_GFX_VERSION: "10.3.0"
      LD_LIBRARY_PATH: "/opt/rocm/lib:/opt/rocm/lib64"
      TZ: "Europe/Amsterdam"
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    group_add:
      - "video"
    volumes:
      - "/opt/rocm:/opt/rocm:ro"
      - "./data:/data"
    command: ["parakeet-rocm", "transcribe", "--output-format", "srt", "--word-timestamps", "--stream", "--batch-size", "42", "--watch", "/data/watch/"]
    restart: unless-stopped
